export const JOB_CATEGORIES = [
  'All',
  'Sales',
  'Customer Success',
  'Account Management',
  'Support',
  'Community',
  'Retail',
  'Hospitality',
  'Operations',
  'Marketing',
  'Product Management',
  'Design',
  'Engineering',
  'Data Science',
  'Finance',
  'HR & People',
  'Legal',
  'Content Creation',
  'Project Management',
  'Business Development',
  'Consulting',
  'Education',
  'Healthcare',
  'Real Estate',
  'Logistics',
] as const;

export type JobCategory = (typeof JOB_CATEGORIES)[number];
